# Generated by Django 4.1.3 on 2022-11-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_library',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
